### ISSUE TITLE
Spotify Track Notifications Show Wrong Album Artwork

### ISSUE THREAD

**Issue by rileyweber13** [lxqt/lxqt-notificationd#133]
When I play music on Spotify, the first notification will display the correct album artwork, but every song after that will continue to show the album artwork of the first song I listened to. I'm not sure what other information to include, as this feels pretty self explanatory to me. What other information would be good?

I hope this is the right place to create this issue. If not, let me know and I'll make the necessary changes.

I'd like to try my hand at fixing this issue myself, but I have no experience with the lxqt project. Could someone point me in the right direction? I've read through the contributing guide but would appreciate specific guidance on where to dig around to debug this specific issue. Hope that's not too much to ask.

Thanks in advance! Here are some screenshots:

![2018-12-19_11-29](https://user-images.githubusercontent.com/25539219/50233846-4df45200-0382-11e9-9b54-e3b0e06c0a4e.png)
![2018-12-19_11-31](https://user-images.githubusercontent.com/25539219/50233847-4df45200-0382-11e9-8055-3b6bdd0c8a99.png)

**Comment by tsujan** [comment]
> ... but every song after that will continue to show the album artwork of the first song I listened to.

How do you know that it's a problem in `lxqt-notificationd` and not `spotify`? Sorry, I can't test `spotify`; could you please check if its notifications are different under KDE (as another Qt based DE)?

> I'd like to try my hand at fixing this issue myself, but I have no experience with the lxqt project.

If you mean the code, all LXQt components are written in C++ and Qt. You also need to know how to make PRs (pull requests) on GitHub (GitHub itself explains that clearly in its doc). Then you could make a PR for your patch and it'll be reviewed by LXQt devs.

But there are other kinds of contributions that are as important as coding, like testing git versions of LXQt apps, translating, proposing new features and, especially, bug reporting.

**Comment by brianweber13** [comment]
> How do you know that it's a problem in lxqt-notificationd and not spotify? ... could you please check if its notifications are different under KDE?
I actually used KDE before switching to lxqt and never had this problem. If you'd like, I could reinstall KDE, switch to it, and test it again.

>If you mean the code
I would love to help writing code! I feel comfortable in c++, but have no experience with Qt. I have used git extensively before and am familiar with pull requests. Should I read some of the Qt documentation before diving in? Could you point me to a file where I can start reading code and learning the codebase? Or maybe point me to files that may be related to this issue?

Thanks again.

**Comment by tsujan** [comment]
> I actually used KDE before switching to lxqt and never had this problem.

So, the problem should be in `lxqt-notificationd` if you have its latest release (do you?).

> If you'd like, I could reinstall KDE, switch to it, and test it again.

No need to that; thanks! We should find another way to reproduce the problem because `spotify` is closed-source and we don't know how it makes those notifications. Or maybe, a deeper look into the code could reveal the issue.

> I feel comfortable in c++, but have no experience with Qt.

It's very good that you're comfortable with C++ and are familiar with git. I can't give you a good advice about how to learn Qt -- I learn things mostly by starting to use them -- but consulting the Qt doc as a reference is a must.

**Comment by agaida** [comment]
@brianweber13 - so you have some big adantages compared to me :) - not comfty with cmake, c++ nor qt - but hey, just a matter of pov :)

**Comment by agaida** [comment]
Hmm - the real thing would be in this case: How to reproduce?

**Comment by brianweber13** [comment]
We could try vlc, but I don't believe I have any mp3s with album artwork. I'm not even sure if vlc shows album art. We could also try qmmp but I've never used it before.

**Comment by palinek** [comment]
First I would suggest to trace down (with e.g. `dbus-monitor`), what `spotify` is sending and compare it to e.g. `notify-send`.

Here is what `notify-send test` does here:
```
method call time=1545292910.582786 sender=:1.34 -> destination=:1.7 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "test"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
method return time=1545292910.621157 sender=:1.7 -> destination=:1.34 serial=29 reply_serial=7
   uint32 1
```

@brianweber13 can you, please, track the "working" and the "non-working" calls of `spotify`?

**Comment by zhrexl** [comment]
I took a look at `dbus-monitor` and `spotify` sends the right icon_data
put a breakpoint on `NotificationLayout::addNotification` and I have no idea as to why but the `hints` argument contains the first `hints` data sent by `spotify` and not the one currently displaying in `dbus-monitor` and thats why it only shows the cover art from the first played song.

I didnt find any info about a similar issue in qt docs

**Comment by zhrexl** [comment]
It took me a while but I finally figured it out.
Spotify sends icon_data and image_data, the last misspelled as image-data and that was the problem.
I'll be opening a new PR soon.

**Comment by tsujan** [comment]
As @zhrexl found out, the problem was about using `image_data`, instead of `image-data`, in the code. It's fixed by @zhrexl in https://github.com/lxqt/lxqt-notificationd/pull/210
