### ISSUE TITLE
lxqt-config-notificationd takes a while to start if notification daemon is not running

### ISSUE THREAD

**Issue by Fat-Zer** [lxqt/lxqt-notificationd#139]
subj;

It looks like lxqt-config-notificationd awaits for some answer on the dbus.

**Comment by tsujan** [comment]
What's the problem? Notification daemon should be running.

**Comment by Fat-Zer** [comment]
It may not be running if it crashed or the configuration GUI is started outside of LXQt. And in that case it looks like it failed to start at first and after some time it suddenly pops up.

**Comment by Fat-Zer** [comment]
@tsujan, KDE config GUI works pretty fine that way ;)

**Comment by Fat-Zer** [comment]
By the word, if you want a relevant use-case for running a configuration UI outside of a session, consider e.g. configuring a remote machine via GUI with tunnelled X-protocol over ssh.

**Comment by tsujan** [comment]
And if one doesn't like to run lxqt-notificationd, why should one want to change its settings?! I see no real use case here.

**Comment by Fat-Zer** [comment]
@agaida, ssh is still a secure minimal-configuration remote client which is preinstall on most systems. I use it occasionally this way if I need just to make small tweaks to remote systems and I don't want to track down configuration file GUI alters. IMHO VNC or RDP would be an overkill and likely will require some interaction with the user (who may be working).

@tsujan, it may be not running at the time of configuration, but one still may want to configure it for later use, I believe this workflow should be supported by all lxqt-config modules.

**Comment by tsujan** [comment]
The question is exactly why you think it's so urgent to configure lxqt-notificationd without running it? Not only that but you also add yet another "should". lxqt-panel "should" be configured without running a panel?! No, it should not.

**Comment by Fat-Zer** [comment]
>The question is exactly why you think it's so urgent to configure lxqt-notificationd without running it?

My rule of thumb: if there is a stand-alone configuration tool it's expected from the tool to work fine regardless the actual app is running or not. Otherwise it's just a bad user experience IMO. It's nothing urgent... but something I believe that should be fixed (especially if it's not difficult).

>Not only that but you also add yet another "should". lxqt-panel "should" be configured without running a panel?! No, it should not.

lxqt-panel doesn't provide a **stand-alone** config tool, so its not relevant here.
e.g. kicker from KDE3 does actually provided such kcontrol config module and it was possible as well to configure it without actually running.

**Comment by tsujan** [comment]
I'm afraid this argument isn't convincing because, as you said, it's just *your* rule of thumb.
