### ISSUE TITLE
Customize behaviour on multi-screen setups

### ISSUE THREAD

**Issue by jmfernandez** [lxqt/lxqt-notificationd#208]
As a laptop, multiscreen user, I would like to customize the behaviour of the notifications when I have more than one attached screen.

##### Expected Behavior

In some moments, I would like the notifications appearing in the screen with the mouse.

Or, maybe, showing the notifications in all the screens.

##### Current Behavior

Notifications always appear in the primary screen.

##### Possible Solution

Enhancing the notifications code, so its behaviour can be set up.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Gentoo
* Kernel: 5.7.7
* Qt Version: 5.14.2
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Although 0.14.1 is outdated, if LXQt notifications don't show up in all screens with the latest version, that's a problem that should be fixed.

Also, an option for showing notifications on screens that contain the mouse cursor would be useful, although I don't know if it could be implemented easily.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-notificationd/pull/209 by @zhrexl

**Comment by jmfernandez** [comment]
Wow, thanks for the hard work!

I still have to test it when next release appears. At least my system is not so outdated than when I opened the issue. I upgraded one month ago to liblxqt to 0.15.1 and lxqt-notificationd to 0.15.0

**Comment by tsujan** [comment]
> At least my system is not so outdated than when I opened the issue. I upgraded one month ago to liblxqt to 0.15.1 and lxqt-notificationd to 0.15.0

We never call the latest release "outdated" but the truth is that it can be far behind the latest git after 5-6 months.
