### ISSUE TITLE
Summary should not be handled as markup

### ISSUE THREAD

**Issue by The-Compiler** [lxqt/lxqt-notificationd#253]
##### Expected Behavior
When sending a notification with the summary `<< test >>`, that text should appear literally.

##### Current Behavior
The text is interpreted as markup and rendered as `>`

##### Possible Solution
Probably call `setTextFormat(Qt::PlainText)` or so on the `summaryLabel`

##### Steps to Reproduce (for bugs)
- `notify-send '<< test >>'` (is displayed wrong)
- `notify-send '&lt;&lt; test &gt;&gt;'` (is displayed as `<< test >>`)

##### Context
See the [notification spec](https://specifications.freedesktop.org/notification-spec/latest/ar01s04.html) (emphasis mine):

> **Body text** may contain markup.

[as well as](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html):

> `"body-markup"`: Supports markup in the **body text**.

##### System Information
Qt 5.15.2 on Archlinux, latest git master.

**Comment by tsujan** [comment]
Right. Markup is for the body text. Thanks for the report!
