### ISSUE TITLE
Texts of action buttons may be cut

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-notificationd#274]
##### Current Behavior

Why should I write tens of lines when I can show the problem with a screenshot? See the button at the middle:

![notification](https://user-images.githubusercontent.com/981076/131234121-6ff330a4-bd43-486b-a468-f2b6b5e91d2d.png)

##### Possible Solution

~I don't think we can use the trick that we used with panel's task buttons because we deal with push buttons here and most styles (if not all) don't consider the lack of space in their case. I'll add a patch to Kvantum for text eliding soon but all other styles will show cut texts.~

EDIT: This would be ideal if possible (the screenshot is taken with the latest git Kvantum, after applying the above-mentioned patch, and the notification is made by `dunstify`):

![elided](https://user-images.githubusercontent.com/981076/131238999-d3c9fd77-e74d-4881-84b1-db643e589b4c.png)

##### System Information

Latest git LXQt

**Comment by stefonarch** [comment]
I think I never saw that issue, but will pay attention now.

**Comment by tsujan** [comment]
> Can you share how you trigger this with dunstify?

Use this in a terminal:

```
dunstify -A "test,Testing a long text Testing a long text Testing a long text" -a 'Test' -t 20000 'Testing a long text.'
```

**Comment by tsujan** [comment]
Oh, I was wrong about the task button trick not working here. It does work :) A screenshot with Fusion after applying it:

![fix](https://user-images.githubusercontent.com/981076/131242493-d8173dee-4da2-4a47-99ed-7872f2e3d09f.png)

Of course, like in task buttons, Breeze is broken here too.

**Comment by stefonarch** [comment]
Yep, I see the issue with that.

**Comment by tsujan** [comment]
@stefonarch 
Please test https://github.com/lxqt/lxqt-notificationd/pull/275 with Fusion. Breeze has the same bug that appeared in Panel's task buttons.

**Comment by stefonarch** [comment]
Yep, breeze is centered, fusion displays fine with  ...

**Comment by tsujan** [comment]
Thanks for testing!

> Yep, breeze is centered

KDE styles share an old bug.

The fix isn't for Kvantum either. Kvantum controls every detail of texts and elides them itself when needed (in its git source — I should make a release but this issue is extremely rare).
