### ISSUE TITLE
Toggle "Do not disturb" from tray

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#289]
Actually we have "Basic Settings" and "advanced". 
When clicking "Settings" in the tray icon (if unattended notifications is active) users arrive at the position setting, the have to switch to "advanced" to change settings.

- [x] Toggle settings' positions
- [x] rename `Basic Settings` > `Position`
- [x] rename `Advanced Settings` > `General (Settings)`
- [x] remove redundant title in "position"
- [x] change icon?
- [x ] move spacing and width settings in ~"Position"~ "Appearance"
- [ ] Toggle "do not disturb" from tray menu

![schermata-12-14-09-02](https://user-images.githubusercontent.com/10681413/145957321-31a013c3-5a57-4b90-aa0f-5effbd6f478f.png)

**Comment by tsujan** [comment]
I agree.

**Comment by stefonarch** [comment]
Actually I'm not fully satisfied yet:
When changing size and spacing users have to switch always  between "General" and "Position" to have a preview.

So logically there should be "General Settings" and "Appearance and Position";  the latter should contain Size, Spazing and "show on screen with mouse cursor":

**Comment by tsujan** [comment]
Personally, I have no problem with the changes you suggested. They just need time. Since rearranging the code may introduce new bugs, it should be done with more care; otherwise, there's no obstacle.

**Comment by stefonarch** [comment]
Stumbled open this, forgot it. Instead of a new issue I make a note here:
"Do not disturb" is away some clicks, could there be an option in the tray menu  to toggle it?

**Comment by tsujan** [comment]
> could there be an option in the tray menu to toggle it?

It should be possible — although I don't remember the code ;)

BTW, we changed the layout; didn't we? Why is this still open?

**Comment by tsujan** [comment]
Oh, sorry, I didn't notice that you re-opened it because of your new suggestion.

**Comment by stefonarch** [comment]
Happened the same to me, why is that open still? ;)

**Comment by stefonarch** [comment]
This is quite messy now to understand, as it's partially achieved and the title has changed as it's about an enhancement (toggle "do not disturb" from systray). I edited the first post.

**Comment by stefonarch** [comment]
I managed to get the item in the right click menu but not the action as `m_area` is not declared here and it should toggle "do not disturb" too. 
https://github.com/lxqt/lxqt-notificationd/blob/63fdeb192b8e7bf0a131278393903de0b014e0cd/src/notifyd.cpp#L266


```
    // "Do not disturb"
    action = m_trayMenu->addAction(QIcon::fromTheme(QSL("notifications-disabled")), tr("Do not disturb"));
   // connect(action, &QAction::triggered, m_trayMenu, [] {
   // m_area->layout()->setDoNotDisturb(m_doNotDisturb);)}

   // "Options"
    action = m_trayMenu->addAction(QIcon::fromTheme(QSL("preferences-system")), tr("Options"));
    connect(action, &QAction::triggered, m_trayMenu, [] {
        QProcess::startDetached(QSL("lxqt-config-notificationd"), QStringList());
    });

```
