### ISSUE TITLE
set _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION

### ISSUE THREAD

**Issue by addy419** [lxqt/lxqt-notificationd#322]
##### Expected Behavior
notification show always stay on top

##### Current Behavior
when using qtile, while notifications do stay on top of terminal and pcmanfm-qt, firefox always stays on top of notifications.

##### Possible Solution
dunst doesn't face this problem, I noticed these xprop parameters on dunst notifications `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_UTILITY` so maybe setting these will work for lxqt-notificationd as well

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: NixOS 22.05 (Quokka)
* Kernel: 5.15.55
* Qt Version: 5.15.3
* liblxqt Version: 1.1.0
* lxqt-build-tools Version: 0.11.0
* Package version: 1.1.0

Edit: I tried `xprop -f _NET_WM_WINDOW_TYPE 32a -set _NET_WM_WINDOW_TYPE _NET_WM_WINDOW_TYPE_NOTIFICATION` and restarted qtile but it still had the same problem so maybe that's not the solution

**Comment by tsujan** [comment]
As we've said repeatedly, LXQt won't add X11 codes to its components.

**Comment by addy419** [comment]
@tsujan the issue still stands, firefox covers lxqt-notificationd. Since dunst worked, I assumed it was related to these properties. If there's an alternate solution, can you suggest it?

**Comment by tsujan** [comment]
> firefox covers lxqt-notificationd.

I've used Firefox for years, and this hasn't happened here.

> when using qtile,...

What's qfile? Does it happen for you without it?

**Comment by addy419** [comment]
qtile is a tiling window manager https://github.com/qtile/qtile. I am using lxqt-notificationd with it. No, it does not happen in vanilla lxqt session.

**Comment by tsujan** [comment]
`lxqt-notificationd` sets all needed flags:

https://github.com/lxqt/lxqt-notificationd/blob/a510b384bf9ae915de55f1b8f542af9a55dd0252/src/notificationarea.cpp#L43-L45

Apparently, qtile doesn't respect that. Adding a workaround for qtile isn't an option, especially when it requires X11 codes.

**Comment by addy419** [comment]
@tsujan thank you for the context. I will continue this issue on qtile's forum.
