### ISSUE TITLE
Notification list has title and border on wayland with some compositors

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#344]
On labwc the window can even be dragged around:

![screen_area_dom_10:17:50_](https://github.com/lxqt/lxqt-notificationd/assets/10681413/e12b24a1-0ab9-47ab-80cf-d9c6024bd523)

Usually it opens  also half out of screen if notification window rule is set to right side. It shouldn't follow window rules at all.
On kwin_wayland title and border are present too.  Wayfire  handles it correctly, hyprland ommits titles by default, ~couldn't test on sway~ on sway it has no border and title but can be dragged around. 

##### Possible Solution

Probably some window flags or attributes can be set.

##### Context

It's one of the 2 issues left with top lxqt-panel on labwc.
##### System Information

* Distribution & Version: latest git, arch

**Comment by tsujan** [comment]
Such problems should be fixed in Wayland compositors. Qt can't tell them what to do.

**Comment by stefonarch** [comment]
Just realized that in wayfire the role is set by the lxqt-desktop-shell plugin, that's probably why it's working only there:
```
Client PID: 238675
Workspace: 1,0
App ID: lxqt-notificationd
Title: lxqt-notificationd
Role: DESKTOP_ENVIRONMENT
Geometry: 1140,48 770x640
Xwayland: false

```

**Comment by tsujan** [comment]
Until a usable and stable `layer-shell-qt`comes out (which I think they've promised for Qt ≥ 6.5), we can do nothing about these things — and it's definitely not possible with Qt5. But Wayland compositors should be able to do virtually anything by adding rules.

**Comment by stefonarch** [comment]
Fixed in https://github.com/lxqt/lxqt-notificationd/pull/345
