### ISSUE TITLE
no remote images in notification

### ISSUE THREAD

**Issue by lodgerz** [lxqt/lxqt-notificationd#380]
Hi, I don't see the images in lxqt notifications, is this normal or is it my problem?
To test use this site:
https://www.bennish.net/web-notifications.html

**Comment by tsujan** [comment]
An image is shown when it exists in the notification, like this:

```sh
notify-send -a 'aria2' -t 5000 -i emblem-downloads 'Download' '<b>Complete!</b>'
```

![image](https://github.com/lxqt/lxqt-notificationd/assets/981076/ad04ff33-1729-4d8e-ab55-7e8bf24d64e6)

**Comment by stefonarch** [comment]
I've had blocked all those notification in firefox, once changed notification settings I got asked to permit them and after agreeing:

![immagine](https://github.com/lxqt/lxqt-notificationd/assets/10681413/20b095c4-5d1b-4032-a413-5061e157b51a)

**Comment by lodgerz** [comment]
no image can be seen on chromium:
![c](https://github.com/lxqt/lxqt-notificationd/assets/9266267/27aedd91-bd65-4731-a576-0d24550e3f85)

**Comment by stefonarch** [comment]
> How did you set up those graphics?

Nothing special to set up, but I can confirm that on chromium the image isn't displayed.

**Comment by stefonarch** [comment]
Hm, maybe the issue is on our side, I stopped the notifications module and started `dunst` and images are displayed in chromium with it:

![immagine](https://github.com/lxqt/lxqt-notificationd/assets/10681413/1927baf7-42b1-48c8-b45b-f1fb05b317a2)

**Comment by stefonarch** [comment]
I see one difference, chromium uses absolute path for icon:

![immagine](https://github.com/lxqt/lxqt-notificationd/assets/10681413/a75cf2eb-a752-4b6d-a6be-0ccac407e7e5)

 Firefox uses a relative path:

![immagine](https://github.com/lxqt/lxqt-notificationd/assets/10681413/171f0901-075c-4e12-8545-9d91cd71963c)

Just downloaded that image  and `notify-send -a 'aria2' -t 5000 -i ~/Sexy_Ben.jpeg 'Test' ` works, while `notify-send -a 'aria2' -t 5000 -i  https://www.bennish.net/images/Sexy_Ben.jpeg  'Test' ` does not display the image.

**Comment by tsujan** [comment]
> So apparently lxqt-notificationd doesn't support remote icons/images.

For whatever reason, that's intentional: https://github.com/lxqt/lxqt-notificationd/blob/3edff5b98d7250a69f36355bd621c3524b342f9e/src/notification.cpp#L274

**Comment by stefonarch** [comment]
What could reason be? It's the first time this shows up as an issue.

**Comment by tsujan** [comment]
> What could reason be?

I can only guess: the delay before fetching remote images may cause problems.

**Comment by stefonarch** [comment]
Just tested mako, like dunst it loads the image too. 

>I can only guess: the delay before fetching remote images may cause problems.

It looks like the only use case for this are those website push notifications which users have to allow explicitly, so I think we should change this, and in any case the icon _is_ remote, it's only the absolute><relative path thing.

**Comment by tsujan** [comment]
Theoretically, it isn't limited to websites — think of SMB, GoogleDrive, etc. If the sender gets the image before notifying (as Firefox does), there will be no problem; otherwise, a long delay will be possible.

**Comment by stefonarch** [comment]
We could test some other notification daemons: if everyone supports remote files I see no reason for us not to permit it.

**Comment by tsujan** [comment]
I have no problem with it, but I wonder if the original coder encountered a bad situation and decided to exclude it, or whether that was just the simplest code that came to his mind.

**Comment by palinek** [comment]
>  if the original coder encountered a bad situation and decided to exclude it, or whether that was just the simplest code that came to his mind.

IMO it was just to distinguish symbolic name and a file path. As previously there were only files supported and the symbolic names were added.

**Comment by tsujan** [comment]
> IMO it was just to distinguish symbolic name and a file path.

Then, using `QNetworkAccessManager`?

**Comment by palinek** [comment]
Yes, seems so. I can have a look into it...

**Comment by palinek** [comment]
Huh, but testing here it seems, that chromium and firefox both download the content of the image. They are just differently presenting it to notification daemon:
- chromium
```method call time=1718212527.605477 sender=:1.160 -> destination=org.freedesktop.Notifications serial=11 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Chromium"
   uint32 0
   string "file:///tmp/.org.chromium.Chromium.MXzLpK"
   string "Notification #1"
   string "<a href="https://www.bennish.net/">www.bennish.net</a>

This is the text body of the notification.
Pretty cool, huh?"
   array [
      string "default"
      string "Activate"
      string "settings"
      string "Settings"
   ]
   array [
      dict entry(
         string "urgency"
         variant             uint32 1
      )
      dict entry(
         string "desktop-entry"
         variant             string "chromium"
      )
      dict entry(
         string "image_path"
         variant             string "/tmp/.org.chromium.Chromium.GhElP2"
      )
      dict entry(
         string "image-path"
         variant             string "/tmp/.org.chromium.Chromium.GhElP2"
      )
   ]
   int32 -1
```
- firefox
```method call time=1718213618.612521 sender=:1.75 -> destination=:1.20 serial=24 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Firefox"
   uint32 0
   string ""
   string "Notification #2"
   string "This is the text body of the notification.
Pretty cool, huh?"
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "suppress-sound"
         variant             boolean false
      )
      dict entry(
         string "image-data"
         variant             struct {
               int32 160
               int32 160
               int32 640
               boolean true
               int32 8
               int32 4
               array of bytes [
                  63 17 09 ff 63 17 09 ff 60 16 09 ff 60 16 09 ff 5e 16 08 ff
                  5e 16 08 ff 5d 18 09 ff 5c 19 09 ff 59 15 08 ff 5a 18 0a ff
                  5b 1c 0d ff 5c 1d 0e ff 5b 1d 10 ff 59 1b 0e ff 59 1b 0e ff
                  5a 1b 0c ff 5d 1b 0b ff 61 1e 0d ff 64 1f 10 ff 64 1f 10 ff
...
                  b3 ad 97 ff b5 ae 9b ff b8 b1 9e ff bb b4 a1 ff be b7 a4 ff
               ]
            }  
      )
      dict entry(
         string "sender-pid"
         variant             int64 5147
      )
   ]
   int32 -1
```
So the question now is why is the temp file unlinked before lxqt-notificationd reads its contents.

**Comment by palinek** [comment]
But there are both `image-path` and `image_path` keys sent (both with the same value). How is that, that one is working and the other not?

**Comment by tsujan** [comment]
I just followed your lead but asked a different question after seeing that hidden image inside `/tmp/`: Why did the code use `getPixmapFromHint` for `image-path`? My guess: a simple copy-paste mistake.

**Comment by lodgerz** [comment]
> That problem is because of this line:
> 
> https://github.com/lxqt/lxqt-notificationd/blob/3edff5b98d7250a69f36355bd621c3524b342f9e/src/notification.cpp#L108
> 
> It should be
> 
> ```c++
> m_pixmap = getPixmapFromString(hints[QL1S("image-path")].toString());
> ```

I confirm that with that change the images can also be seen on chromium. Thank you! :-)

**Comment by palinek** [comment]
> That problem is because of this line:
> 
> https://github.com/lxqt/lxqt-notificationd/blob/3edff5b98d7250a69f36355bd621c3524b342f9e/src/notification.cpp#L108
> 
> It should be
> 
> ```c++
> m_pixmap = getPixmapFromString(hints[QL1S("image-path")].toString());
> ```

@tsujan  Will you make PR for it? (I don't want to steal your contribution)

**Comment by tsujan** [comment]
> Will you make PR for it?

I will. It was a team work, whose main part was your [comment](https://github.com/lxqt/lxqt-notificationd/issues/380#issuecomment-2163577105).

@lodgerz, thanks for reporting the problem.
