### ISSUE TITLE
Positioning on active monitor (with cursor) doesn't work on wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#382]
There is a checkbox: "show on monitor with cursor" which does nothing under wayland.

##### Expected Behavior

Notifications should appear where cursor is.
##### Current Behavior

They appear always on first monitor.
##### Possible Solution

Similar to https://github.com/lxqt/lxqt-runner/pull/286 ?
##### Steps to Reproduce (for bugs)

1. Check the checkbox
2. test notifications

* Distribution & Version:  git, all, arch

**Comment by tsujan** [comment]
Thanks. I'll fix it like in https://github.com/lxqt/lxqt-runner/pull/286.
