### ISSUE TITLE
Possible regression: notification background is missing

### ISSUE THREAD

**Issue by Bluey26** [lxqt/lxqt-notificationd#406]
##### Expected Behavior

LXQt notifications should have a background color, which depends on color palette assigned in lxqt-config-appearance

![previous](https://github.com/user-attachments/assets/41569767-5478-4d76-a645-9a3f8f30576f)

##### Current Behavior

LXQt notifications lack the background, instead the text is shown over the current window.

![testnotification](https://github.com/user-attachments/assets/9e00b13c-a76e-4456-a893-36493bb99209)

##### Steps to Reproduce (for bugs)

1. Install lastest lxqt-notificationd from source or archlinux repositories
2. Test notifications, there is no background.

##### Context

I was using a mix of 2.0 and 2.1 packages, and the notification background was present in my system a few hours ago. After the update i noticed that there was no background. I decided to test a few things, and i downgraded lxqt-notificationd from 2.1-> https://github.com/lxqt/lxqt-notificationd/commit/98716f6dde32f6a7ad24a0ce0544150095923edc

After restarting the lxqt-notification daemon from session settngs, there was background present.

The issue may be related to the next commit: https://github.com/lxqt/lxqt-notificationd/commit/65c518a0b0200e840f1464846e7c7c36a2639291
which i suspected to be related because it was about translucency (that's why i have chosen a previous commit to test).

##### System Information

* Distribution & Version:  Archlinux
* Kernel: Linux 6.11.7-arch1-1
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0
* lxqt-build-tools Version: 2.1.0
* Package version: 2.1.0

**Comment by Bluey26** [comment]
> Not reproducible with 2.1.0.
> 
> Make sure you've compiled it against Qt 6.8.
> 
> BTW, you forgot to tell that it happened _under Wayland_ for you; didn't it? Also, please tell which LXQt theme you use.

I used the official package and also compiled it myself https://archive.archlinux.org/packages/l/lxqt-notificationd/lxqt-notificationd-2.1.0-1-x86_64.pkg.tar.zst , is the one in the arch repos.


> OK, you don't use any stylesheet for lxqt-notificationd — it should be the System theme. Yes, I can see it too, without that stylesheet and _under Wayland_.

Yes, i use System theme, a custom version. I now see that changing it to another LXQt theme seems to provide a background according to it. I thought it was related to palette, i confused it because System theme uses color palette for the colors.

**Comment by tsujan** [comment]
The simple fix is here: https://github.com/lxqt/lxqt-notificationd/pull/407. Thanks for reporting!

**Comment by Bluey26** [comment]
> The simple fix is here: #407. Thanks for reporting!

On the contrary, thanks to you for this quick fix, it works properly now :)

**Comment by tsujan** [comment]
My second thank for testing it :)
