### ISSUE TITLE
Wayland: Notifications always appear in the center of the screen

### ISSUE THREAD

**Issue by nobake2048** [lxqt/lxqt-notificationd#410]
##### Expected Behavior

Notifications should appear at the location configured.

##### Current Behavior

On Wayfire, notifcations always appear in the center of the screen

##### Steps to Reproduce (for bugs)

1. Open lxqt-config-notificationd
2. Click Preview. The preview will appear centered on screen.
3. Or wait until you get a notification from another application.
 

##### System Information

* Distribution & Version:  Arch Linux
* Kernel: linux-lts-6.6.64
* Qt Version: 6.8.1
* liblxqt Version: 2.1.0
* lxqt-build-tools Version: 
* Package version: 2.1.1

**Comment by tsujan** [comment]
> On Wayfire, notifcations always appear in the center of the screen

If so, the problem is in Wayfire.

Make sure you haven't set a position rule that can affect notifications to your Wayfire config file.

**Comment by stefonarch** [comment]
Wayfire doesn't have rules for layer surfaces afaik, but probably  there is something in the config. Just tested on debian, no issue.

**Comment by tsujan** [comment]
>  Just tested it on debian, no issue.

Good, but even if there was an issue with the default config file of Wayfire, it should be reported to Wayfire.

**Comment by nobake2048** [comment]
Did some more testing.
First I just switched over to mako that I was using in my sway session. That works correctly, placing in the corner as expected.
Did some reading on Wayfire. The "place" plugin (included in your Wayfire configuration) will by default place new windows in the center of the screen. Disabling this plugin does not get the notif placement to work correctly, but it does move from the center to the top-left corner.
Finally, paying more attention I see that - at least for me - the lxqt notifications are being opened as new windows as evidenced by showing up in the taskbar, thus they are showing in the center of the screen.

So if you guys are sure this is a Wayfire issue I will go open an issue over there. But in my admittedly naive opinion this looks like a problem with the use of layer-shell.
Or I suppose there could just be something really weird going on with my setup. stefonarch say it works for them and all.
![2024-12-11_18:16:30](https://github.com/user-attachments/assets/d1613627-6f34-458c-b1ff-3a181c1f1e47)

**Comment by stefonarch** [comment]
Can you share here `~/.config/lxqt/lxqt-wayfire.conf`? Some plugin can apparently transform the layer surface to a window which is weird. Did you test any other compositor, e.g. labwc?

**Comment by stefonarch** [comment]
Just to be sure about the version:
```
lxqt-notificationd -v
```

**Comment by nobake2048** [comment]
Current config. Had to add .txt for github to let me upload it. This was based on the wayfire config shipped by lxqt, customized mostly for hotkeys.
[lxqt-wayfire.ini.txt](https://github.com/user-attachments/files/18119683/lxqt-wayfire.ini.txt)

```
lxqt-notificationd -v
lxqt-notificationd 2.1.1
liblxqt   2.1.0
Qt        6.8.0
```

I tried the default wayfire config provided by lxqt, as well as sway and labwc. All exhibited the same behavior here.

**Comment by stefonarch** [comment]
As it happens with other compositors too the reason isn't in the config, I tested it nevertheless, all fine here.  

This issue is present only with the notifications or do you see in the taskbar also `lxqt-runner` or the "leave" dialog?

You could also stop the notifications module in "Session Settings" and starting it with
` WAYLAND_DEBUG=1 lxqt-notificationd 2> /tmp/log.txt.`, then open `lxqt-config` and make one test notification, stop the process and attach the log here.

**Comment by stefonarch** [comment]
Maybe it is for some reason running under xwayland? Can be checked running `xeyes`, it will move when the cursor is over an xwayland application.

**Comment by nobake2048** [comment]
[log.txt](https://github.com/user-attachments/files/18126076/log.txt)

Checked xeyes, and the notifications do appear to running on Wayland.

Later today when I have more time I will create a fresh user and test if things work under that.

**Comment by nobake2048** [comment]
Okay, finally found a solution, if not the root cause.
I created the test user and found that if I logged in via terminal and launched startlxqtwayland session the notifications worked (*mostly, see end note) as expected. But if I logged in via my normal login manager (greetd/QtGreet) I would have the issues.
I switched over to SDDM and the behavior is the same as launching from terminal, as expected. No idea why the login manager should make a difference, but it seems it does.

Thank you much for helping me with troubleshooting, even though in the end it turned out to really not be your problem.

*I did find that changing the setting for the position of the notification will not update until stopping and restarting the notification daemon, but that's a different issue. I can open separate bug report for that if you want, I'm just happy things are set up right on my end now.

**Comment by tsujan** [comment]
> I did find that changing the setting for the position of the notification will not update until stopping and restarting the notification daemon

Not reproducible. Here it changes as soon as the setting is changed, as expected.

**Comment by stefonarch** [comment]
> *I did find that changing the setting for the position of the notification will not update until stopping and restarting the notification daemon, but that's a different issue. I can open separate bug report for that if you want, I'm just happy things are set up right on my end now

You mean in the preview? There it updates position only when there is no notification shown anymore.

I'm using greetd too, with `command = "tuigreet --remember -i -t --remember-session --cmd startlxqtwayland"` so the issue could be in QtQreet

**Comment by marcusbritanicus** [comment]
It's nothing to do with QtGreet. All the QtGreet does is inform greetd the command to be invoked. For LXQt Wayland Session, the command will simply be `startlxqtwayland`.

As an aside, but related note, I would like to add that in my case, the notifications just do not show when I use lxqt-notificationd. They work fine with other notification daemons, for example, mako and desq-notifier. Of course, I am not using LXQt Session, but I think that should not matter.

**Comment by nobake2048** [comment]
> You mean in the preview? There it updates position only when there is no notification shown anymore.

I did not know or expect that. Waiting a couple seconds after letting the notification expire does allow the position to update. All good on that front.

Again, I can't imagine why QtGreet would have been the issue. As far as I understand, it should just launch whatever commend is in the Exec line of the desktop file, which is just startlxqtwayland. But nonetheless, not using it fixed the problem.

**Comment by stefonarch** [comment]
>the notifications just do not show when I use lxqt-notificationd. 

That's interesting... confirming.

I started a pure labwc session, started `lxqt-notificationd &` and noticed the same. But opening once `lxqt-config-notificationd` and selecting a position  it will work normally.

**Comment by tsujan** [comment]
> … and noticed the same.

Strange. More than a year ago, I used LXQt components, and especially, lxqt-notificationd — which wasn't fully ready for Wayland at that time — under Wayfire and without an LXQt session. I didn't like any other notification system because they lacked a way of showing “unattended” notifications. And LXQt notifications worked like a charm.
